language: go
go: 
 - 1.2
 - 1.3
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/tools/godep
 - go install -a -race std

script:
 - godep restore
 - go tool vet -all .
 - godep go test -v -race ./...
