language: go
go: 
 - release
 - tip
 
install:
 - mkdir ${HOME}/bin
 - export PATH=${PATH}:${HOME}/bin
 - export GOBIN=${HOME}/bin
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/tools/godep
 - go get github.com/golang/lint/golint

script:
 - golint .
 - godep restore
 - go vet ./...
 - godep go test -v -race ./...
