language: go
go: 
 - 1.2
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/tools/godep
 - export PATH=${PATH}:${HOME}/gopath/bin

script:
 - godep restore
 - go vet ./...
 - go fmt ./...
 - godep go test -v -race ./... -gocheck.v
