language: go
go: 
 - release
 - tip
 
install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get github.com/tools/godep
 - export PATH=${PATH}:${HOME}/gopath/bin
 - go install -a -race std
 - go get github.com/golang/lint/golint

script:
 - golint .
 - godep restore
 - go tool vet -all .
 - godep go test -v -race ./...
