language: go
go: 
 - 1.2
 - release
 - tip
 
install:
 - go get gopkg.in/check.v1
 - go get github.com/cheggaaa/pb
 - go get github.com/codegangsta/cli
 - go get github.com/guelfey/go.dbus
 - go get code.google.com/p/go.tools/cmd/vet

script:
 - go test -v -race ./... -gocheck.v
 - go vet ./...
 - go fmt ./...
